module.exports = {
  PROFILE_COMPLETED: +5,
  STARTUP_CREATED: +3,
  STARTUP_VERIFIED: +10,
  JOB_POSTED: +2,
  AD_APPROVED: +5,

  FRAUD_REPORTED_VALID: -15,
  FRAUD_CONFIRMED: -25,
  AD_REJECTED: -10,
  SPAM_ACTIVITY: -5
};
